### ISSUE TITLE
hello,This is the term of 15

### ISSUE THREAD

**Issue by YX1900** [HaoZhang95/Python24#13]
hello,you are wrong,this is the term of 15.It isn't the term of 24

**Comment by HaoZhang95** [comment]
你好，readme中的讲义是24期的，视频的话，python24视频是加密的，无法分享。但是readme中的python视频教程内容是最接近python24的，只是期数问题。讲解的内容基本一致，再配合讲义文档，不要太在意python几期。祝学有所成
