### ISSUE TITLE
视频教程没有美多商城

### ISSUE THREAD

**Issue by jianjun6** [HaoZhang95/Python24#15]

**Comment by jianjun6** [comment]
当前的视频教程是15期的。可以提供一下24期的链接吗？非常感谢！！！！

**Comment by HaoZhang95** [comment]
仓库简介中说明了原因，因为美多商城使用的vue技术栈，并不是html

**Comment by jianjun6** [comment]
可以发一份24期教程吗？非常想学习美多商城。------------------ 原始邮件 ------------------
发件人: "Hao Zhang"<notifications@github.com>
发送时间: 2019年12月6日(星期五) 凌晨2:10
收件人: "HaoZhang95/Python24"<Python24@noreply.github.com>;
抄送: "jianjun6"<1634783872@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [HaoZhang95/Python24] 视频教程没有美多商城 (#15)



仓库简介中说明了原因，因为美多商城使用的vue技术栈，并不是html
 
&mdash;
