### ISSUE TITLE
讲义链接失效

### ISSUE THREAD

**Issue by Lucifer0103** [HaoZhang95/Python24#24]
第二套讲义链接失效了, 还得麻烦您 抽空更新下链接, 期待回复中...

**Comment by xinaliu2134** [comment]
第二套讲义链接失效,热切期待更新 感谢！

**Comment by markshui** [comment]
第二套讲义链接失效,热切期待更新 感谢！

**Comment by zoujiawei0329** [comment]
第二套讲义链接失效,热切期待更新 感谢！

**Comment by sunyunxian** [comment]
第二套讲义失效啦。

**Comment by HaoZhang95** [comment]
> 第二套讲义链接失效了, 还得麻烦您 抽空更新下链接, 期待回复中...

已更新连接, 请查看https://github.com/HaoZhang95/Python24 的最新readme文件

**Comment by HaoZhang95** [comment]
> 第二套讲义失效啦。

已更新连接, 请查看https://github.com/HaoZhang95/Python24 的最新readme文件

**Comment by HaoZhang95** [comment]
> 第二套讲义链接失效,热切期待更新 感谢！

已更新连接, 请查看https://github.com/HaoZhang95/Python24 的最新readme文件

**Comment by HaoZhang95** [comment]
> 第二套讲义链接失效了, 还得麻烦您 抽空更新下链接, 期待回复中...

已更新连接, 请查看https://github.com/HaoZhang95/Python24 的最新readme文件

**Comment by sunyunxian** [comment]
> > 第二套讲义链接失效了, 还得麻烦您 抽空更新下链接, 期待回复中...
> 
> 已更新连接, 请查看[https://github.com/HaoZhang95/Python24 的最新readme文件](https://github.com/HaoZhang95/Python24%C2%A0%E7%9A%84%E6%9C%80%E6%96%B0readme%E6%96%87%E4%BB%B6)

thanks

**Comment by karenther** [comment]
404

**Comment by HaoZhang95** [comment]
> 404

刚试了, 百度云的各项链接均没失效
