### ISSUE TITLE
下载的就业班视频中的有个视频是错误的（之前章节的视频），原章节视频未见。

### ISSUE THREAD

**Issue by 1491035393** [HaoZhang95/Python24#52]
错误视频路径：就业班/06 mini-web框架v3.1/05-mini-web框架添加正则和log日志功能/02-股票列表

**Comment by HaoZhang95** [comment]
24期：链接: https://pan.baidu.com/s/1Q9ZFKk81P42T6CVyJzp9dA?pwd=b7ju 提取码: b7ju
37期：链接: https://pan.baidu.com/s/1hKF6ZSiFQk79-BDb6b7TFA?pwd=8wb1 提取码: 8wb1
