### ISSUE TITLE
大侠，视频地址过期了！

### ISSUE THREAD

**Issue by feihao02** [HaoZhang95/Python24#7]
望再次补上！谢谢！！因怕链接秒挂，或私链发我邮箱一下939838080@qq.com

**Comment by HaoZhang95** [comment]
链接已更新，请查看readme

**Comment by feihao02** [comment]
谢谢大侠！不过你是否发错连接了呢？这还是15期的，不是24期的呀。和你git上面的目录也对不上。麻烦大侠看能否再重新发一遍。



---原始邮件---
发件人: "Hao Zhang"<notifications@github.com&gt;
发送时间: 2019年11月5日(星期二) 晚上8:04
收件人: "HaoZhang95/Python24"<Python24@noreply.github.com&gt;;
抄送: "feihao02"<939838080@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [HaoZhang95/Python24] 大侠，视频地址过期了！ (#7)



链接已更新，请查看readme
