### ISSUE TITLE
你好，第二套讲义的下载地址

### ISSUE THREAD

**Issue by iamzxj** [HaoZhang95/Python24#73]
你好，第二套讲义的下载地址好像失效了

**Comment by HaoZhang95** [comment]
24期：链接: https://pan.baidu.com/s/1Q9ZFKk81P42T6CVyJzp9dA?pwd=b7ju 提取码: b7ju
37期：链接: https://pan.baidu.com/s/1hKF6ZSiFQk79-BDb6b7TFA?pwd=8wb1 提取码: 8wb1
